import json
import os
import sys
import urllib.error
import urllib.request
from google import genai
from google.genai import types

MAX_DIFF_BYTES = 200_000

def main():
    # 1. Fetch required environment variables
    api_key = os.getenv("GEMINI_API_KEY")
    repo_name = os.getenv("REPO_NAME")
    pr_number = os.getenv("PR_NUMBER")
    github_token = os.getenv("GITHUB_TOKEN")

    if not api_key or not repo_name or not pr_number:
        print("Missing required environment variables. Exiting.")
        sys.exit(1)

    # 2. Read the PR diff file generated by the workflow
    diff_path = "pr_diff.txt"
    if not os.path.exists(diff_path) or os.path.getsize(diff_path) == 0:
        print("No changes found or diff file is empty.")
        sys.exit(0)

    with open(diff_path, "r", encoding="utf-8", errors="ignore") as f:
        pr_diff = f.read()

    if len(pr_diff) > MAX_DIFF_BYTES:
        pr_diff = pr_diff[:MAX_DIFF_BYTES] + "\n\n[... diff truncated — too large to review in full ...]"
        print(f"Warning: diff exceeded {MAX_DIFF_BYTES} bytes and was truncated.")

    # 3. Initialize the Gemini Client
    client = genai.Client(api_key=api_key)

    # 4. Construct System Instructions & Prompts
    system_instruction = (
        "You are an expert Motorola 6809 and Hitachi 6309 assembly optimizer "
        "and a NitrOS-9 operating system kernel architect.\n\n"
        "Your task is to review a unified git diff for a Pull Request. "
        "Focus on finding severe logical bugs, architectural violations, or regressions. "
        "Ignore superficial stylistic differences or minor spacing updates.\n\n"
        "Critically evaluate the code for the following anti-patterns:\n"
        "1. Register Clobbering: Are registers (A, B, D, X, Y, U) modified inside a subroutine "
        "without being safely preserved on the stack via PSHS and restored via PULS?\n"
        "2. OS-9 Error Handling: Does the code fail to check the Carry bit (BCS/BCC) immediately "
        "following an OS-9 system call status return (e.g., os9 F$Link)?\n"
        "3. Missing Returns: Do execution paths inside new or modified subroutines fail to end with RTS or RTI?\n"
        "4. Critical Optimization: Is an expensive loop structure introduced where a simpler shift, addition, or "
        "6309-native instruction (if applicable) could save precious CPU cycles?\n\n"
        "Strictly enforce the following repository-specific rules:\n"
        "- **6309 Hardware Specific Optimizations**: When targeting 6309 hardware specifically (e.g. within H6309 blocks), "
        "mandatorily emit `TFM X+,Y+` or `TFM X-,Y-` and completely bypass software loops to hit the 3.00 cycles/byte hardware limit.\n"
        "- **Standard 6809 Buffer Optimizations (≤ 16 Bytes)**: When optimizing small-to-medium variable buffers up to 16 bytes "
        "on standard 6809, utilize constant 5-bit offsets (`LDD n,Y` / `STD n,X`) in an unrolled structure instead of auto-increment "
        "adjustments to save 2.00 cycles per byte. Ensure `LEAX`/`LEAY` are emitted at the end of the unrolled block to correctly align "
        "base pointers if loop processing repeats.\n"
        "- **'Stack Blast' Routines using LDS**: Prepend stack blast routines with `ORCC #$50` and append with `ANDCC #$AF`. "
        "If these are omitted, mark code generation as FAILED.\n"
        "- **Overlapping Memory Blocks (Source < Destination)**: When memory blocks overlap such that Source < Destination, "
        "calculate pointers from the end of the buffers moving backward via pre-decrement operators `,--X` or negative 5-bit offsets "
        "to maintain data integrity.\n\n"
        "NitrOS-9 System Call Reference Notes:\n"
        "- F$Link: Expects entry module name pointer in X. Returns module entry point in Y, updated header pointer in U. Success clears Carry bit.\n"
        "- F$Fork: Expects module name pointer in X. Returns process ID in A. Clears Carry bit on success.\n\n"
        "Formatting: Provide your review in clean Markdown. Start with a brief summary table. "
        "If no critical bugs or issues are found, reply exactly with: 'NO_ISSUES_DETECTED'."
    )

    user_prompt = f"Please review the following git unified diff:\n\n```diff\n{pr_diff}\n```"

    # 5. Call the Model (Using gemini-2.5-flash for speed and low cost)
    print("Sending diff to Gemini for analysis...")
    try:
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,
                temperature=0.2,
            )
        )
        review_text = response.text.strip()
    except Exception as e:
        print(f"Gemini API error: {e}. Skipping review.")
        sys.exit(0)

    # 6. Bypass posting if the model flags no severe errors
    if review_text == "NO_ISSUES_DETECTED":
        print("Gemini found no severe bugs. Skipping PR comment.")
        sys.exit(0)

    # 7. Post the response back to the GitHub PR via the REST API
    print("Posting review feedback back to GitHub PR...")

    url = f"https://api.github.com/repos/{repo_name}/issues/{pr_number}/comments"
    body = json.dumps({"body": f"### 🤖 Automated Gemini PR Review\n\n{review_text}"}).encode()

    req = urllib.request.Request(
        url,
        data=body,
        headers={
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3+json",
            "Content-Type": "application/json",
        },
        method="POST",
    )

    try:
        with urllib.request.urlopen(req) as resp:
            if resp.status == 201:
                print("Review posted successfully.")
            else:
                print(f"Unexpected response status: {resp.status}")
                sys.exit(1)
    except urllib.error.HTTPError as e:
        print(f"Error posting comment: HTTP {e.code} {e.reason}")
        sys.exit(1)

if __name__ == "__main__":
    main()
